### ISSUE TITLE
The bndlr icon does not appear in notification area of taskbar

### ISSUE THREAD

**Issue by Shimi9999** [bmssearch/bndlr#1]
bndlr-0.1.0.Setup.exeでインストール後、タスクバーの通知領域にbndlrのアイコンが表示されず、機能を利用できません。
タスクマネージャーを見ると、バックグラウンドプロセスにbndlrが3つ立ち上がっています。

OS: Windows 10 Version 20H2 Build 19042.928

**Comment by yuto-hasegawa** [comment]
報告ありがとうございます。

こちらでキャッシュを削除して試してみたところ確かに再現しました。
キャッシュを消さずにリリース前のチェックを行ってしまっていたため発見できなかったようです。

対処させていただきます。

**Comment by yuto-hasegawa** [comment]
bndlrのプロセスが3つ立ち上がっていること自体は正常な動作となります。

**Comment by yuto-hasegawa** [comment]
@Shimi9999 
修正版をリリースしました！
今回はデータベース周りで致命的な箇所が見つかったため、先にv0.1.0のデータを削除する必要があります。
お手数ですがリリースノートに記載の手順で更新をお願いします。
https://github.com/bmssearch/bndlr/releases/tag/v0.1.1

**Comment by yuto-hasegawa** [comment]
動作が確認できましたらクローズの上アナウンスを行おうと思います。
お手数ですが確認とれましたらご一報いただけると幸いです。

**Comment by Shimi9999** [comment]
手順通りに更新を行った後、動作を確認できました。
ご対応ありがとうございました。

**Comment by yuto-hasegawa** [comment]
確認ありがとうございました！
