### ISSUE TITLE
マニフェストの取得に失敗する

### ISSUE THREAD

**Issue by mironak** [bmssearch/bndlr#2]
bmssearch.netのイベント会場からbndlrリンクを開くと、「グループマニフェストを取得できませんでした」が出てインストールリストが作成されません。
通知では原因の表示が見切れていましたが、おそらく以下のようなサーバーの認証局の変更の影響と思われます。
https://github.com/oliverschwendener/ueli/issues/807#issuecomment-932851049

v0.1.1
OS: Windows 10 Version 21H2 Build 19044.1526

**Comment by yuto-hasegawa** [comment]
報告ありがとうございます！
どうやらelectronのバージョンを上げる必要がありそうですね…

**Comment by yuto-hasegawa** [comment]
https://github.com/bmssearch/bndlr/releases/tag/v0.1.2
electronを最新バージョンにアップグレードし、こちらの問題に対処しました。
